name: .NET Console Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build and Run Program
      run: |
        dotnet new console -o MyConsoleApp
        mv Program.cs MyConsoleApp/Program.cs
        dotnet run --project MyConsoleApp
