name: .NET Console Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Set up Console Project and Add Program.cs
      run: |
        # Remove the MyConsoleApp directory if it already exists
        if (Test-Path -Path MyConsoleApp) { Remove-Item -Recurse -Force MyConsoleApp }
        
        # Create a new console project in MyConsoleApp directory
        dotnet new console -o MyConsoleApp
        # Move Program.cs from the pipeline folder to the new project directory
        mv pipeline/Program.cs MyConsoleApp/Program.cs

    - name: Build and Run Program
      run: dotnet run --project MyConsoleApp
