name: .NET Console Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Set up Console Project and Add Program.cs
      run: |
        dotnet new console -o MyConsoleApp                     # Create a new console project in the MyConsoleApp directory.
        mv pipeline/Program.cs MyConsoleApp/Program.cs         # Move Program.cs from the pipeline folder to MyConsoleApp.
        
    - name: Build and Run Program
      run: dotnet run --project MyConsoleApp
